MOARDOTS_loot_table = {
--- ONYXIA ---
{["loot_id"] = "18423", ["loot_name"] = "Head of Onyxia", ["prio"] = "Tanks = Physical DPS"},
{["loot_id"] = "17067", ["loot_name"] = "Ancient Cornerstone Grimoire", ["prio"] = "*PVP*"},
{["loot_id"] = "18813", ["loot_name"] = "Ring of Binding", ["prio"] = "N/A"},
{["loot_id"] = "17078", ["loot_name"] = "Sapphiron Drape", ["prio"] = "Casters > Healers"},
{["loot_id"] = "18205", ["loot_name"] = "Eskhandar's Collar", ["prio"] = "Tanks > *PVP*"},
{["loot_id"] = "17068", ["loot_name"] = "Deathbringer", ["prio"] = "Axe weapon choice"},
{["loot_id"] = "17064", ["loot_name"] = "Shard of the Scale", ["prio"] = "Healers"},
{["loot_id"] = "17075", ["loot_name"] = "Vis'Kag the Bloodletter", ["prio"] = "Sword weapon choice"},

--- BWL ---
-- Razorgore
{["loot_id"] = "19337", ["loot_name"] = "The Black Book", ["prio"] = "Warlock > *PVP*"},
{["loot_id"] = "19336", ["loot_name"] = "Arcane Infused Gem", ["prio"] = "Hunter > *PVP*"},
{["loot_id"] = "19369", ["loot_name"] = "Gloves of Rapid Evolution", ["prio"] = "Healer or Disenchant"},
{["loot_id"] = "19370", ["loot_name"] = "Mantle of the Blackwing Cabal", ["prio"] = "SPriest > Mage = Warlock"},
{["loot_id"] = "19335", ["loot_name"] = "SpineShatter", ["prio"] = "Tanks > 1H FWarrior"},
{["loot_id"] = "19334", ["loot_name"] = "The Untamed Blade", ["prio"] = "DPS Warrior"},
{["loot_id"] = "19340", ["loot_name"] = "Rune of Metamorphosis", ["prio"] = "Druid"},
-- Vaelastrasz
{["loot_id"] = "19371", ["loot_name"] = "Pendant of the Fallen Dragon", ["prio"] = "Healers"},
{["loot_id"] = "19372", ["loot_name"] = "Helm of Endless Rage", ["prio"] = "Warrior Tank > DPS Warrior", ["note"] = "Fury tank prio"},
{["loot_id"] = "19346", ["loot_name"] = "Dragonfang Blade", ["prio"] = "Rogues = Fury Tank > DPS Warrior"},
{["loot_id"] = "19348", ["loot_name"] = "Red Dragonscale Protector", ["prio"] = "RShaman"},
{["loot_id"] = "19339", ["loot_name"] = "Mind Quickening Gem", ["prio"] = "Mage"},
-- Broodlord Lashlayer
{["loot_id"] = "19373", ["loot_name"] = "Black Brood Pauldrons", ["prio"] = "Shaman > Hunters"},
{["loot_id"] = "19341", ["loot_name"] = "Lifegiving Gem", ["prio"] = "Tanks > *PVP*", ["note"] = "(Loot Council)"},
{["loot_id"] = "19374", ["loot_name"] = "Bracers of Arcane Accuracy", ["prio"] = "Warlock = Mage > SPriest", ["note"] = "Warlock Tank prio"},
{["loot_id"] = "19350", ["loot_name"] = "Heartstriker", ["prio"] = "Melee"},
{["loot_id"] = "19351", ["loot_name"] = "Maladath, Runed Blade of the Black Flight", ["prio"] = "Rogue = DPS Warrior > Fury tank", ["note"] = "Sword-wielders, (Loot Council)"},
-- Loot pinatas
{["loot_id"] = "19399", ["loot_name"] = "Black Ash Robe", ["prio"] = "Fire res"},
{["loot_id"] = "19400", ["loot_name"] = "Firemaw's Clutch", ["prio"] = "Casters"},
{["loot_id"] = "19365", ["loot_name"] = "Claw of the Black Drake", ["prio"] = "DPS Warriors > *PVP*"},
{["loot_id"] = "19398", ["loot_name"] = "Cloak of Firemaw", ["prio"] = "Rogue > Warrior > Hunter"},
{["loot_id"] = "19396", ["loot_name"] = "Taut Dragonhide Belt", ["prio"] = "Melee"},
{["loot_id"] = "19394", ["loot_name"] = "Drake Talon Pauldrons", ["prio"] = "DPS Warriors = Fury tanks", ["note"] = "(Loot Council)"},
{["loot_id"] = "19397", ["loot_name"] = "Ring of Blackrock", ["prio"] = "Healers = SPriest"},
{["loot_id"] = "19344", ["loot_name"] = "Natural Alignment Crystal", ["prio"] = "RShaman > EnhShaman"},
{["loot_id"] = "19401", ["loot_name"] = "Primalist's Linked Legguards", ["prio"] = "EleShaman = EnhShaman"},
{["loot_id"] = "19395", ["loot_name"] = "Rejuvenating Gem", ["prio"] = "Healers", ["note"] = "(Loot Council)"},
{["loot_id"] = "19355", ["loot_name"] = "Shadow Wing Focus Staff", ["prio"] = "Caster DPS > RDruid > *PVP*"},
{["loot_id"] = "19353", ["loot_name"] = "Drake Talon Cleaver", ["prio"] = "EnhShaman = DPS Warrior > *PVP*"},
{["loot_id"] = "19345", ["loot_name"] = "Aegis of Preservation", ["prio"] = "*PVP*"},
{["loot_id"] = "19403", ["loot_name"] = "Band of Forced Concentration", ["prio"] = "Warlock = Mage > SPriest"},
{["loot_id"] = "19406", ["loot_name"] = "Drake Fang Talisman", ["prio"] = "Melee > Fury Tank > Hunter", ["note"] = "Veteran Melee DPS, (Loot Council)"},
{["loot_id"] = "19407", ["loot_name"] = "Ebony Flame Gloves", ["prio"] = "SPriest = Warlock "},
{["loot_id"] = "19405", ["loot_name"] = "Malfurion's Blessed Bulwark", ["prio"] = "DPS Warrior = EnhShaman"},
{["loot_id"] = "19368", ["loot_name"] = "Dragonbreath Hand Cannon", ["prio"] = "Tank > Melee > *PVP*"},
{["loot_id"] = "19430", ["loot_name"] = "Shroud of Pure Thought", ["prio"] = "RShaman = RDruid = HPriest", ["note"] = "(Loot Council)"},
{["loot_id"] = "19432", ["loot_name"] = "Circle of Applied Force", ["prio"] = "Tanks = DPS Warrior > Rogue"},
{["loot_id"] = "19433", ["loot_name"] = "Emberweave Leggings", ["prio"] = "FWarrior = Enh. Shaman = Hunter who needs FR"},
{["loot_id"] = "19431", ["loot_name"] = "Styleen's Impeding Scarab", ["prio"] = "Tank"},
{["loot_id"] = "19367", ["loot_name"] = "Dragon's Touch", ["prio"] = "Casters > Priests"},
-- Chromaggus
{["loot_id"] = "19388", ["loot_name"] = "Angelista's Grasp", ["prio"] = "Warlock = Mage"},
{["loot_id"] = "19389", ["loot_name"] = "Taut Dragonhide Shoulderpads", ["prio"] = "Melee"},
{["loot_id"] = "19387", ["loot_name"] = "Chromatic Boots", ["prio"] = "DPS Warrior = FTank", ["note"] = "(Loot Council)"},
{["loot_id"] = "19390", ["loot_name"] = "Taut Dragonhide Gloves", ["prio"] = "RDruid"},
{["loot_id"] = "19391", ["loot_name"] = "Shimmering Geta", ["prio"] = "Healers"},
{["loot_id"] = "19386", ["loot_name"] = "Elementium Threaded Cloak", ["prio"] = "Tank", ["note"] = "Prot warrior prio"},
{["loot_id"] = "19385", ["loot_name"] = "Empowered Leggings", ["prio"] = "HPriests = RDruid > RShaman"},
{["loot_id"] = "19352", ["loot_name"] = "Chromatically Tempered Sword", ["prio"] = "SRogue > DPS Warrior", ["note"] = "Sword-wielders, (Loot Council)"},
{["loot_id"] = "19347", ["loot_name"] = "Claw of Chromaggus", ["prio"] = "Casters = Healers"},
{["loot_id"] = "19393", ["loot_name"] = "Primalist's Linked Waistguard", ["prio"] = "*PVP*"},
{["loot_id"] = "19361", ["loot_name"] = "Ashjre'thul, Crossbow of Smiting", ["prio"] = "Hunter > Melee"},
{["loot_id"] = "19349", ["loot_name"] = "Elementium Reinforced Bulwark", ["prio"] = "Tank"},
-- Nefarian
{["loot_id"] = "19002", ["loot_name"] = "Head of Nefarian", ["prio"] = "Melee = Hunters"},
{["loot_id"] = "19378", ["loot_name"] = "Cloak of the Brood Lord", ["prio"] = "Mage = SPriest = Warlock"},
{["loot_id"] = "19381", ["loot_name"] = "Boots of the Shadow Flame", ["prio"] = "Druid Tank > Rogue > EnhShaman", ["note"] = "(Loot Council)"},
{["loot_id"] = "19380", ["loot_name"] = "Therazane's Link", ["prio"] = "EnhShaman > Hunter"},
{["loot_id"] = "19376", ["loot_name"] = "Archimtiros' Ring of Reckoning", ["prio"] = "Tank > *PVP*"},
{["loot_id"] = "19379", ["loot_name"] = "Neltharion's Tear", ["prio"] = "Warlock = Mage > SPriest", ["note"] = "Warlock Tank prio, (Loot Council)"},
{["loot_id"] = "19382", ["loot_name"] = "Pure Elementium Band", ["prio"] = "Healers"},
{["loot_id"] = "19375", ["loot_name"] = "Mish'undare, Circlet of the Mind Flayer", ["prio"] = "Mage = Warlock = SPriest"},
{["loot_id"] = "19377", ["loot_name"] = "Prestor's Talisman of Connivery", ["prio"] = "Rogue = Hunter", ["note"] = "(Loot Council)"},
{["loot_id"] = "19356", ["loot_name"] = "Staff of the Shadow Flame", ["prio"] = "Warlock = Mage"},
{["loot_id"] = "19364", ["loot_name"] = "Ashkandi, Greatsword of the Brotherhood", ["prio"] = "2H FWarrior = Hunters", ["note"] = "*PVP* item"},
{["loot_id"] = "19363", ["loot_name"] = "Crul'shorukh, Edge of Chaos", ["prio"] = "DPS Warrior", ["note"] = "Axe-wielders, Orcs first, (Loot Council)"},
{["loot_id"] = "19360", ["loot_name"] = "Lok'amir il Romathis", ["prio"] = "Healers > SPriests", ["note"] = "(Loot Council)"},
-- Trash
{["loot_id"] = "19436", ["loot_name"] = "Cloak of Draconic Might", ["prio"] = "DPS Warrior > Tank > Melee", ["note"] = "(Loot Council)"},
{["loot_id"] = "19439", ["loot_name"] = "Interlaced Shadow Jerkin", ["prio"] = "*PVP*"},
{["loot_id"] = "19437", ["loot_name"] = "Boots of Pure Thought", ["prio"] = "RDruid > HPriest / RShaman"},
{["loot_id"] = "19438", ["loot_name"] = "Ringo's Blizzard Boots", ["prio"] = "Mage"},
{["loot_id"] = "19434", ["loot_name"] = "Band of Dark Dominion", ["prio"] = "SPriest = Warlock"},
{["loot_id"] = "19362", ["loot_name"] = "Doom's Edge", ["prio"] = "FTank = DPS Warrior", ["note"] = "Prio with 305 skill, (Loot Council)"},
{["loot_id"] = "19435", ["loot_name"] = "Essence Gatherer", ["prio"] = "Casters = Healers"},
{["loot_id"] = "19358", ["loot_name"] = "Draconic Maul", ["prio"] = "*PVP*"},
{["loot_id"] = "19354", ["loot_name"] = "Draconic Avenger", ["prio"] = "*PVP*"},

--- MC ---
-- Lucifron
{["loot_id"] = "17109", ["loot_name"] = "Choker of Enlightenment", ["prio"] = "Caster DPS > Healer"},
{["loot_id"] = "18872", ["loot_name"] = "Manastorm Leggings", ["prio"] = "Healers"},
{["loot_id"] = "18861", ["loot_name"] = "Flamewalker Legplates", ["prio"] = "Tank > Fire resist"},
{["loot_id"] = "18879", ["loot_name"] = "Heavy Dark Iron Ring", ["prio"] = "Tank"},
{["loot_id"] = "19147", ["loot_name"] = "Ring of Spell Power", ["prio"] = "Mage > Warlock"},
{["loot_id"] = "19145", ["loot_name"] = "Robe of Volatile Power", ["prio"] = "Casters"},
{["loot_id"] = "18870", ["loot_name"] = "Helm of the Lifegiver", ["prio"] = "RShaman"},
{["loot_id"] = "17077", ["loot_name"] = "Crimson Shocker", ["prio"] = "Casters > FResist"},
{["loot_id"] = "18875", ["loot_name"] = "Salamander Scale Pants", ["prio"] = "RShaman = RDruid"},
{["loot_id"] = "18878", ["loot_name"] = "Sorcerous Dagger", ["prio"] = "Casters > Healers"},
{["loot_id"] = "19146", ["loot_name"] = "Wristguards of Stability", ["prio"] = "DPS Warrior"},
-- Magmadar
{["loot_id"] = "17073", ["loot_name"] = "Earthshaker", ["prio"] = "Off Tanks > *PVP*"},
{["loot_id"] = "17069", ["loot_name"] = "Striker's Mark", ["prio"] = "DPS Warrior = Warrior = Tank"},
{["loot_id"] = "17065", ["loot_name"] = "Medallion of Steadfast Might", ["prio"] = "Tanks"},
{["loot_id"] = "18203", ["loot_name"] = "Eskhandar's Right Claw", ["prio"] = "Tanks > Melee"},
{["loot_id"] = "19143", ["loot_name"] = "Flameguard Gauntlets", ["prio"] = "DPS Warrior > Tank Warrior"},
{["loot_id"] = "18821", ["loot_name"] = "Quick Strike Ring", ["prio"] = "Melee > Hunter"},
{["loot_id"] = "18823", ["loot_name"] = "Aged Core Leather Gloves", ["prio"] = "DRogue > SRogue"},
{["loot_id"] = "19142", ["loot_name"] = "Fire Runed Grimoire", ["prio"] = "Casters"},
{["loot_id"] = "19136", ["loot_name"] = "Mana Igniting Cord", ["prio"] = "Mage > Warlock"},
{["loot_id"] = "18822", ["loot_name"] = "Obsidian Edged Blade", ["prio"] = "DPS Warrior", ["note"] = "non-orc prio"},
{["loot_id"] = "18820", ["loot_name"] = "Talisman of Ephemeral Power", ["prio"] = "Casters"},
{["loot_id"] = "18829", ["loot_name"] = "Deep Earth Spaulders", ["prio"] = "EleShaman *PVP"},
{["loot_id"] = "19144", ["loot_name"] = "Sabatons of the Flamewalker", ["prio"] = "EnhShaman > *PVP*"},
-- Gehennas
-- Garr
{["loot_id"] = "17105", ["loot_name"] = "Aurastone Hammer", ["prio"] = "Shaman > Druid"},
{["loot_id"] = "18832", ["loot_name"] = "Brutality Blade", ["prio"] = "SRogue > DPS Warrior > Hunters"},
{["loot_id"] = "17066", ["loot_name"] = "Drillborer Disk", ["prio"] = "Prot Tank"},
{["loot_id"] = "17071", ["loot_name"] = "Gutgore Ripper", ["prio"] = "DRogue = DPS Warrior = Tank"},
{["loot_id"] = "18564", ["loot_name"] = "Bindings of the Windseeker", ["prio"] = "Rad wishes"},
-- Shazzrah
-- Baron Geddon
{["loot_id"] = "17110", ["loot_name"] = "Seal of the Archmagus", ["prio"] = "*PVP*"},
{["loot_id"] = "18563", ["loot_name"] = "Bindings of the Windseeker", ["prio"] = "Loot Council"},
-- Golemag the Incinerator
{["loot_id"] = "17103", ["loot_name"] = "Azuresong Mageblade", ["prio"] = "Mage = Warlock"},
{["loot_id"] = "18842", ["loot_name"] = "Staff of Dominance", ["prio"] = "Casters > Healers"},
{["loot_id"] = "17072", ["loot_name"] = "Blastershot Launcher", ["prio"] = "DPS Warrior = Rogue = Tank"},
-- Sulfuron Harbinger
{["loot_id"] = "17074", ["loot_name"] = "Shadowstrike", ["prio"] = "Vendor Strike"},
-- Majordomo Executus
{["loot_id"] = "18808", ["loot_name"] = "Gloves of the Hypnotic Flame", ["prio"] = "Casters *PVP*"},
{["loot_id"] = "19140", ["loot_name"] = "Cauterizing Band", ["prio"] = "Healers"},
{["loot_id"] = "18806", ["loot_name"] = "Core Forged Greaves", ["prio"] = "*Fire Resist*"},
{["loot_id"] = "18810", ["loot_name"] = "Wild Growth Spaulders", ["prio"] = "Healer"},
{["loot_id"] = "18811", ["loot_name"] = "Fireproof Cloak", ["prio"] = "Tank > *Fire Resist*"},
{["loot_id"] = "18805", ["loot_name"] = "Core Hound Tooth", ["prio"] = "DRogue > SRogue"},
{["loot_id"] = "18803", ["loot_name"] = "Finkle's Lava Dredger", ["prio"] = "*PVP*"},
{["loot_id"] = "19139", ["loot_name"] = "Fireguard Shoulders", ["prio"] = "Tank > *Fire Resist*"},
{["loot_id"] = "18809", ["loot_name"] = "Sash of Whispered Secrets", ["prio"] = "Warlock = SPriest"},
{["loot_id"] = "18812", ["loot_name"] = "Wristguards of True Flight", ["prio"] = "Tanks = EnhShaman > Hunter"},
{["loot_id"] = "18646", ["loot_name"] = "The Eye of Divinity", ["prio"] = "Priests"},
{["loot_id"] = "18703", ["loot_name"] = "Ancient Petrified Leaf", ["prio"] = "Hunters", ["note"] = "Prio with sinew"},
-- Ragnaros
{["loot_id"] = "18815", ["loot_name"] = "Essence of the Pure Flame", ["prio"] = "*PVP*"},
{["loot_id"] = "19138", ["loot_name"] = "Band of Sulfuras", ["prio"] = "*PVP*"},
{["loot_id"] = "17102", ["loot_name"] = "Cloak of the Shrouded Mists", ["prio"] = "Hunter > Melee = Tank"},
{["loot_id"] = "17107", ["loot_name"] = "Dragon's Blood Cape", ["prio"] = "Tanks > DPS Warrior > *PVP*"},
{["loot_id"] = "17106", ["loot_name"] = "Malistar's Defender", ["prio"] = "Shaman"},
{["loot_id"] = "18816", ["loot_name"] = "Perdition's Blade", ["prio"] = "DRogue > SRogue"},
{["loot_id"] = "19137", ["loot_name"] = "Onslaught Girdle", ["prio"] = "FTank and DPS Warrior"},
{["loot_id"] = "17063", ["loot_name"] = "Band of Accuria", ["prio"] = "Tank > Melee > Hunter"},
{["loot_id"] = "18814", ["loot_name"] = "Choker of the Fire Lord", ["prio"] = "Casters"},
{["loot_id"] = "18817", ["loot_name"] = "Crown of Destruction", ["prio"] = "Enh. Shaman > Hunter > DPS Warrior"},
{["loot_id"] = "17082", ["loot_name"] = "Shard of the Flame", ["prio"] = "Disenchant"},
{["loot_id"] = "17076", ["loot_name"] = "Bonereaver's Edge", ["prio"] = "DPS Warrior", ["note"] = "dual-wielders"},
{["loot_id"] = "17104", ["loot_name"] = "Spinal Reaper", ["prio"] = "DPS Warrior = EnhShaman > *PVP*"},

--- ZG ---
-- Jeklik
{["loot_id"] = "19920", ["loot_name"] = "Primalist's Band", ["prio"] = "Healers", ["note"] = "Prio for set completion"},
-- Venoxis
{["loot_id"] = "19907", ["loot_name"] = "Zulian Tigerhide Cloak", ["prio"] = "Melee = Tanks = Hunter"},
{["loot_id"] = "19905", ["loot_name"] = "Zanzil's Band", ["prio"] = "Casters", ["note"] = "Prio for set completion"},
-- Mar'li
{["loot_id"] = "19925", ["loot_name"] = "Band of Jin", ["prio"] = "Melee = Hunter", ["note"] = "Prio for set completion"},
-- Mandokir
{["loot_id"] = "20038", ["loot_name"] = "Mandokir's Sting", ["prio"] = "Melee"},
{["loot_id"] = "19866", ["loot_name"] = "Warblade of the Hakkari 1", ["prio"] = "Rogue > Melee"},
{["loot_id"] = "19863", ["loot_name"] = "Primalist's Seal", ["prio"] = "Healers", ["note"] = "Prio for set completion"},
{["loot_id"] = "19893", ["loot_name"] = "Zanzil's Seal", ["prio"] = "Casters", ["note"] = "Prio for set completion"},
-- Gahz'Ranka
{["loot_id"] = "19947", ["loot_name"] = "Nat Pagle's Broken Reel", ["prio"] = "Tanks > Warlock Tanks", ["note"] = "Hit For: 4 Horsemen Naxxramas"},
{["loot_id"] = "22739", ["loot_name"] = "Tome of Polymorph: Turtler", ["prio"] = "Mage"},
-- Thekal
{["loot_id"] = "19897", ["loot_name"] = "Betrayer's Boots", ["prio"] = "Casters = Healers"},
{["loot_id"] = "19898", ["loot_name"] = "Seal of Jin", ["prio"] = "Melee = Hunter", ["note"] = "Prio for set completion"},
{["loot_id"] = "19901", ["loot_name"] = "Zulian Slicer", ["prio"] = "Skinners prio"},
-- Arlokk
{["loot_id"] = "19909", ["loot_name"] = "Will of Arlokk", ["prio"] = "RDruid = Mage", ["note"] = "Highest spirit weapon for innervate/Evocation"},
-- Jin'do
{["loot_id"] = "19885", ["loot_name"] = "Jin'do's Evil Eye", ["prio"] = "Healers"},
{["loot_id"] = "19891", ["loot_name"] = "Jin'do's Bag of Whammies", ["prio"] = "Warlock > Mage"},
{["loot_id"] = "19890", ["loot_name"] = "Jin'do's Hexxer", ["prio"] = "RShaman = RDruid > HPriest"},
{["loot_id"] = "19886", ["loot_name"] = "The Hexxer's Cover", ["prio"] = "SPriest > Warlock > Mage"},
-- Hakkar
{["loot_id"] = "19857", ["loot_name"] = "Cloak of Consumption", ["prio"] = "Casters"},
{["loot_id"] = "19856", ["loot_name"] = "The Eye of Hakkar", ["prio"] = "2H FWarrior"},
{["loot_id"] = "19861", ["loot_name"] = "Touch of Chaos", ["prio"] = "Caster DPS (Healers buy BOE green instead)"},
{["loot_id"] = "19865", ["loot_name"] = "Warblade of the Hakkari 2", ["prio"] = "Hunter"},
{["loot_id"] = "19859", ["loot_name"] = "Fang of the Faceless", ["prio"] = "Hunter > DRogue > 1H FWarrior"},
{["loot_id"] = "19802", ["loot_name"] = "Heart of Hakkar", ["prio"] = "Caster DPS without TOEP > Healers"},
-- Misc/shared
{["loot_id"] = "22637", ["loot_name"] = "Primal Hakkari Idol", ["prio"] = "Queue system as needed for AQ loot"},
{["loot_id"] = "22721", ["loot_name"] = "Band of Servitude", ["prio"] = "Mage = SPriest > Warlock"},

--- AQ20 ---
-- General Rajaxx
{["loot_id"] = "21493", ["loot_name"] = "Boots of the Vanguard", ["prio"] = "Rogue / FWarrior / Ferals"},
{["loot_id"] = "21495", ["loot_name"] = "Legplates of the Qiraji Command", ["prio"] = "FWarrior"},
-- Ossirian the Unscarred
{["loot_id"] = "21457", ["loot_name"] = "Bracers of Brutality", ["prio"] = "DPS Warrior"},
{["loot_id"] = "21462", ["loot_name"] = "Gloves of Dark Wisdom", ["prio"] = "Healing Priest"},
{["loot_id"] = "21459", ["loot_name"] = "Crossbow of Imminent Doom", ["prio"] = "Warrior Tank > Melee"},
{["loot_id"] = "21461", ["loot_name"] = "Leggings of the Black Blizzard", ["prio"] = "Mage > Spriest"},
{["loot_id"] = "21220", ["loot_name"] = "Head of Ossirian the Unscarred", ["prio"] = "Healers = Caster DPS"},
-- Trash and shared loot
{["loot_id"] = "21801", ["loot_name"] = "Antenna of Invigoration", ["prio"] = "Healers"},
{["loot_id"] = "20885", ["loot_name"] = "Qiraji Martial Drape", ["prio"] = "(Cloak Revered) DPS Warrior > Rogue"},
{["loot_id"] = "20888", ["loot_name"] = "Qiraji Ceremonial Ring", ["prio"] = "(Ring Honored) Rolled on if its upgrade"},
{["loot_id"] = "20884", ["loot_name"] = "Qiraji Magisterial Ring", ["prio"] = "(Ring Honored) Rolled on if its upgrade"},
{["loot_id"] = "20890", ["loot_name"] = "Qiraji Ornate Hilt", ["prio"] = "(Weapons Exalted) Rolled on if its upgrade"},
{["loot_id"] = "20886", ["loot_name"] = "Qiraji Spiked Hilt", ["prio"] = "(Weapons Exalted) Rolled on if its upgrade"},

--- AQ40 ---
-- The prophet Skeram
{["loot_id"] = "21701", ["loot_name"] = "Cloak of Concentrated Hatred", ["prio"] = "Rogue = EnhShaman > DPS Warriors", ["note"] = "warrs get similar from aq20"},
{["loot_id"] = "21814", ["loot_name"] = "Breastplate of Annihilation", ["prio"] = "DPS Warrior"},
-- Battleguard Sartura
{["loot_id"] = "21672", ["loot_name"] = "Gloves of Enforcement", ["prio"] = "Rogue > EnhShaman", ["note"] = "SRogue > DRogue"},
{["loot_id"] = "21670", ["loot_name"] = "Badge of the Swarmguard", ["prio"] = "DPS Warrior = Hunter > Melee"},
{["loot_id"] = "21666", ["loot_name"] = "Sartura's Might", ["prio"] = "Healers"},
{["loot_id"] = "21673", ["loot_name"] = "Silithid Claw", ["prio"] = "Hunters > Melee"},
-- Fankriss the Unyielding
{["loot_id"] = "21663", ["loot_name"] = "Robes of the Guardian Saint", ["prio"] = "HPriest = RDruid > RShaman"},
{["loot_id"] = "21650", ["loot_name"] = "Ancient Qiraji Ripper", ["prio"] = "SRogue = DPS FWarrior", ["note"] = "prio for Sword wielders"},
{["loot_id"] = "21651", ["loot_name"] = "Scaled Sand Reaver Leggings", ["prio"] = "EnhShaman > DPS Warrior"},
{["loot_id"] = "22396", ["loot_name"] = "Totem of Life", ["prio"] = "RShaman"},
-- Princess Huhuran
{["loot_id"] = "20932", ["loot_name"] = "Qiraji Bindings of Dominance", ["prio"] = "Warlock = Mage = RShaman", ["note"] = "Shamans(Both), Mages(Boots), Warlocks(Shoulders)"},
{["loot_id"] = "20928", ["loot_name"] = "Qiraji Bindings of Command", ["prio"] = "Rogue = Tank = DPS Warrior", ["note"] = "Rogues(Both), Tank(Shoulders),DPS(Shoulders)"},
{["loot_id"] = "21618", ["loot_name"] = "Hive Defiler Wristguards", ["prio"] = "DPS Warriors"},
{["loot_id"] = "21617", ["loot_name"] = "Wasphide Gauntlets", ["prio"] = "RDruid > RShaman"},
{["loot_id"] = "21620", ["loot_name"] = "Ring of the Martyr", ["prio"] = "Healers"},
-- Twin Emperors (Vek'lor/Vek'nilash)
{["loot_id"] = "20930", ["loot_name"] = "Vek'lor's Diadem", ["prio"] = "Rogue = RShaman", ["note"] = "(Helmet)"},
{["loot_id"] = "21600", ["loot_name"] = "Boots of Epiphany", ["prio"] = "SPriest > Casters"},
{["loot_id"] = "21597", ["loot_name"] = "Royal Scepter of Vek'lor", ["prio"] = "Mage = Warlock"},
{["loot_id"] = "21602", ["loot_name"] = "Qiraji Execution Bracers", ["prio"] = "Rogue > EnhShaman"},
{["loot_id"] = "20926", ["loot_name"] = "Vek'nilash's Circlet", ["prio"] = "Warlock > Tank = SPriest", ["note"] = "(Helmet)"},
{["loot_id"] = "21609", ["loot_name"] = "Regenerating Belt of Vek'nilash", ["prio"] = "RDruid > RShaman"},
{["loot_id"] = "21604", ["loot_name"] = "Bracelets of Royal Redemption", ["prio"] = "HPriest = RDruid > RShaman"},
{["loot_id"] = "21608", ["loot_name"] = "Amulet of Vek'nilash", ["prio"] = "Mage = Warlock"},
-- C'Thun
{["loot_id"] = "21221", ["loot_name"] = "Eye of C'Thun", ["prio"] = "FTank = Casters = Healers"},
{["loot_id"] = "20929", ["loot_name"] = "Carapace of the Old God", ["prio"] = "Tank = Rogue = RShaman", ["note"] = "(Chest)"},
{["loot_id"] = "20933", ["loot_name"] = "Husk of the Old God", ["prio"] = "SPriest", ["note"] = "(Chest)"},
{["loot_id"] = "22731", ["loot_name"] = "Cloak of the Devoured", ["prio"] = "Casters"},
{["loot_id"] = "21581", ["loot_name"] = "Gauntlets of Annihilation", ["prio"] = "DPS Warriors"},
{["loot_id"] = "21839", ["loot_name"] = "Scepter of the False Prophet", ["prio"] = "Healers"},
{["loot_id"] = "21583", ["loot_name"] = "Cloak of Clarity", ["prio"] = "Healers"},
{["loot_id"] = "21585", ["loot_name"] = "Dark Storm Gauntlets", ["prio"] = "Casters"},
{["loot_id"] = "21582", ["loot_name"] = "Grasp of the Old God", ["prio"] = "HPriest = RDruid > RShaman"},
{["loot_id"] = "21586", ["loot_name"] = "Belt of Never-ending Agony", ["prio"] = "Rogue > EnhShaman"},
{["loot_id"] = "21134", ["loot_name"] = "Dark Edge of Insanity", ["prio"] = "DPS Warrior = EnhSHaman", ["note"] = "Prio for Two-handed wielders"},
{["loot_id"] = "21126", ["loot_name"] = "Death's Sting", ["prio"] = "Rogue", ["note"] = "Prio for Dagger wielders"},
-- Bug Trio (Yauj/Vem/Kri)
{["loot_id"] = "21694", ["loot_name"] = "Ternary Mantle", ["prio"] = "HPriest = RShaman > RDruid"},
{["loot_id"] = "21688", ["loot_name"] = "Boots of the Fallen Hero", ["prio"] = "FTank = DPS Warriors"},
{["loot_id"] = "21690", ["loot_name"] = "Angelista's Charm", ["prio"] = "Healers"},
{["loot_id"] = "21603", ["loot_name"] = "Wand of Qiraji Nobility", ["prio"] = "Casters"},
{["loot_id"] = "21681", ["loot_name"] = "Ring of the Devoured", ["prio"] = "RShaman"},
-- Viscidus
{["loot_id"] = "21624", ["loot_name"] = "Gauntlets of Kalimdor", ["prio"] = "EnhShaman"},
{["loot_id"] = "22399", ["loot_name"] = "Idol of Health", ["prio"] = "RDruid"},
{["loot_id"] = "21677", ["loot_name"] = "Ring of the Qiraji Fury", ["prio"] = "DPS Warrior > Melee = Hunter"},
{["loot_id"] = "21622", ["loot_name"] = "Sharpened Silithid Femur", ["prio"] = "Mage = Warlock"},
-- Ouro
{["loot_id"] = "20931", ["loot_name"] = "Skin of the Great Sandworm", ["prio"] = "RShaman", ["note"] = "(Leggings)"},
{["loot_id"] = "20927", ["loot_name"] = "Ouro's Intact Hide", ["prio"] = "Tank = Rogue > SPriest", ["note"] = "(Helm)"},
{["loot_id"] = "21615", ["loot_name"] = "Don Rigoberto's Lost Hat", ["prio"] = "HPriest = RDruid > RShaman"},
{["loot_id"] = "23557", ["loot_name"] = "Larvae of the Great Worm", ["prio"] = "Hunter > Melee"},
{["loot_id"] = "21610", ["loot_name"] = "Wormscale Blocker", ["prio"] = "RShaman"},
{["loot_id"] = "21611", ["loot_name"] = "Burrower Bracers", ["prio"] = "SPriest > Casters"},
{["loot_id"] = "23570", ["loot_name"] = "Jom Gabbar", ["prio"] = "Rogue = Hunter > DPS Warrior"},
-- Trash and shared loot
{["loot_id"] = "21232", ["loot_name"] = "Imperial Qiraji Armaments", ["prio"] = "Rogue = DPS Warrior", ["note"] = "DRogue & Axe Warriors"},
{["loot_id"] = "21237", ["loot_name"] = "Imperial Qiraji Regalia", ["prio"] = "Warlock = Mage > Healer"},
{["loot_id"] = "21836", ["loot_name"] = "Ritssyn's Ring of Chaos", ["prio"] = "Mage = Warlock > SPriest"},

}
